name: My simple action

on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          title: Test title
          body: Test body
          assignees: |
            olehlavryk
            oleh-lavryk-dev
      - run: |
          echo ${{steps.issue.outputs.issue}}
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greed: World!
      - run: echo "Time ${{steps.hello.outputs.time}}"
      - run: echo $HELLO
